[package]
name = "wasm-fortune"
version = "0.1.0"
authors = ["bbarekas"]
edition = "2018"

[dependencies]
rand = "0.8.3"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.70"

[lib]
name = "getfortune"
crate-type =["cdylib", "lib"]